### ISSUE TITLE
Setting up Deno Environment for TypeScript

### ISSUE THREAD

**Issue by Shyam-Chen** [krahets/hello-algo#1186]
> https://www.hello-algo.com/chapter_appendix/installation/#7-javascript

Should we add [Deno](https://deno.com/) environment for TypeScript to the "编程环境安装"?

The syntax support for JavaScript includes the option of Deno:
<img width="651" alt="image" src="https://github.com/krahets/hello-algo/assets/13535256/290d7c70-ec44-4927-9923-2a2c063db032">

**Comment by krahets** [comment]
I think it largely depends on whether Deno is popular enough (or if there is a trend towards it).

A similar case is that we generally install Python by installing Anaconda, rather than installing Python directly.

As far as I know, JavaScript and TypeScript run mostly on node.js. Deno looks great! But I'm not sure which is a better choice for freshers, node.js or Deno?

**Comment by Shyam-Chen** [comment]
Alternatively, [TypeScript Execute (tsx)](https://github.com/privatenumber/tsx) can be used to execute TypeScript files instead of `node`:

```sh
$ npm install tsx --global
```

```sh
 ~/Documents/hello-algo/ [main] tsx ./codes/typescript/chapter_searching/binary_search.ts
目标元素 6 的索引 = 2
目标元素 6 的索引 = 2
```

Frankly, I haven't been using Deno in a production environment either, just for small tools at most.

**Comment by krahets** [comment]
Can we debug the code with [TypeScript Execute (tsx)](https://github.com/privatenumber/tsx)? We prefer installing a debugger so that people can use breakpoints

**Comment by Shyam-Chen** [comment]
Yes, its commands are the same as Node.js.

**Comment by krahets** [comment]
I would recommend choosing `ts-node` or `tsx` after seeing https://github.com/privatenumber/ts-runtime-comparison . `tsx` looks like simpler to use.

Please add the installation steps at your convenience, thanks!
