### ISSUE TITLE
手机或者移动端搜索不展开问题

### ISSUE THREAD

**Issue by Lizhenghe-Chen** [krahets/hello-algo#1589]
**发现应该是由于高斯模糊导致的问题**
![image](https://github.com/user-attachments/assets/c2934d34-2270-4225-9e83-379dfe1e06df)

简单的修复如下：
```
.md-header {
  backdrop-filter: saturate(120%) blur(3px);
  /* Gaussian blur */
  -webkit-backdrop-filter: saturate(120%) blur(3px);
  /* Safari */
  background-color: var(--md-header-bg-color);
}

/* 移动端样式 */
@media (max-width: 1000px) {
  .md-header {
    backdrop-filter: none;
    /* 移动端禁用虚化 */
    -webkit-backdrop-filter: none;
    /* Safari 移动端禁用虚化 */
    background-color: rgba(255, 255, 255, 0.8);
    /* 使用半透明背景色 */
  }
}
```

**Comment by krahets** [comment]
谢谢反馈！我希望可以在移动端保留高斯模糊效果，但目前还没有找到完美的解决方案（目前移动端 Chrome 已经正常、Safari 仍有问题）。

**Comment by krahets** [comment]
Fixed in 40261ca762722c05393fa11fe79552ac087f4196

Tests on iPhone:

Safari:
<img src="https://github.com/user-attachments/assets/0c6dd922-b4e0-4b43-8fe8-698a0477a373" alt="Safari" width="400">

Chrome:
<img src="https://github.com/user-attachments/assets/fc8bc565-5f5b-4490-8008-1552b8e9c4f3" alt="Chrome" width="400">
